wish_custom = '~r~擲筊前請說明你要請示之事項'
doing_custom = '~g~你正在擲筊'
wrong_place = '你不在廟前，無法擲筊'
wait = '你擲太多次了，慢一點'
TossResult_nice = '~g~聖筊'
TossResult_nice_mean = '~g~表示神明允許、同意，或行事會順利'
TossResult_hmmm = '~o~笑筊'
TossResult_hmmm_mean = '~o~這代表著神明表示神明一笑、不解，或者考慮中'
TossResult_nah = '~r~陰筊'
TossResult_nah_mean = '~r~這代表著神明不允許這件事'
TossResult = '的擲筊結果'
got_money = '~g~你獲得了發財金8888'

